### PR TITLE
Team2 department component

### PR DESCRIPTION
**Pull request by williammartinez10**
If any changes are required let me know.

### CODE REVIEW

**Comment by williammartinez10** [comment]
#29

**Review by panchi64 — CHANGES_REQUESTED** [review]
Sorry to ask this of you basically at the last second, could you make this component using the React Native Paper library? That way we can maintain some uniformity throughout the project.

I think the only code you would need to change would be from line 15 to 28 in the DepartmentComponent.js file.

**Comment by williammartinez10** [comment]
Done, the component was modified using react native paper.

**Comment by panchi64** [comment]
Perfect, I'll resolve the merge conflict real quick and merge it

**Pull request merged**
