### PR TITLE
created profile page with non functional component

### PR DESCRIPTION
**Pull request by print-Eruki**

### CODE REVIEW

**Comment by panchi64** [comment]
Seems good to me. Later on, I think it might be a good idea to move out all code of the pages from the App.js to their own dedicated .js/.jsx files.

**Review by panchi64 — APPROVED** [review]
Seems good to me. Later on, I think it might be a good idea to move out all code of the pages from the App.js to their own dedicated .js/.jsx files.

**Review by G4vp — APPROVED** [review]

**Review by OrdepA17 — APPROVED** [review]
The page looks great, later on we can restructure the files to have dedicated .js for each page and a concrete color palette.

**Comment by panchi64** [comment]
Is this going to be reviewed and approved for merge by team1 any time soon?

**Pull request merged**
